--- #This playbook will upgrade java on the machince
- hosts: all
  remote_user: hadoop
  become_method: sudo
  gather_facts: yes
  connection: ssh
  tasks:
  - name: aiflow installation
    shell: |
       sudo yum -y update
       sudo yum install -y gcc
       sudo yum install -y python-setuptools
       yes y | sudo -H pip uninstall six==1.9.0
       yes y | sudo -H pip install six==1.10.0
       yes y | sudo -H pip install Sphinx
       yes y | sudo -H pip uninstall markupsafe
       yes y | sudo -H pip install markupsafe==0.23
       yes y | sudo -H pip install airflow
       yes y | sudo -H pip install "apache-airflow[s3, postgres]"
       airflow initdb
       airflow webserver -p 7777
    become: true
