#This code will install Presto Admin version 2.x on the machine.
---
- hosts: all
  tasks:
   - name: update
     shell: |
       rm -rf presto*
       sudo yum update all
       sudo yum -y install python2-devel gcc
       sudo wget https://github.com/prestodb/presto-admin/releases/download/2.3/prestoadmin-2.3-online.tar.gz
       sudo tar xvf prestoadmin*
       chown hadoop:hadoop *
       cd prestoadmin
       ./install-prestoadmin.sh
     become: true
